export const SET_LOADING_STATE = 'CORE/SET_LOADING_STATE';

export const DEFAULT_ROUTE_QUERY_START = 'CORE/DEFAULT_ROUTE_QUERY_START';
export const DEFAULT_ROUTE_QUERY_SUCCESS = 'CORE/DEFAULT_ROUTE_QUERY_SUCCESS';
export const DEFAULT_ROUTE_QUERY_ERROR = 'CORE/DEFAULT_ROUTE_QUERY_ERROR';

export const ROUTE_QUERY_START = 'CORE/ROUTE_QUERY_START';
export const ROUTE_QUERY_SUCCESS = 'CORE/ROUTE_QUERY_SUCCESS';
export const ROUTE_QUERY_ERROR = 'CORE/ROUTE_QUERY_ERROR';

export const LOGIN_START = 'CORE/LOGIN_START';
export const LOGIN_SUCCESS = 'CORE/LOGIN_SUCCESS';
export const LOGIN_ERROR = 'CORE/LOGIN_ERROR';
export const LOGIN_CLEAR = 'CORE/LOGIN_CLEAR';

export const SHOW_ALERT = 'CORE/SHOW_ALERT';
export const CLEAR_ALERT = 'CORE/CLEAR_ALERT';

export const HARD_RESET = 'CORE/HARD_RESET';
