export const SET_LOADING_STATE = 'CORE/SET_LOADING_STATE';
export const DEFAULT_ROUTE_QUERY_START = 'CORE/DEFAULT_ROUTE_QUERY_START';
export const DEFAULT_ROUTE_QUERY_SUCCESS = 'CORE/DEFAULT_ROUTE_QUERY_SUCCESS';
export const DEFAULT_ROUTE_QUERY_ERROR = 'CORE/DEFAULT_ROUTE_QUERY_ERROR';
export const ROUTE_QUERY_START = 'CORE/ROUTE_QUERY_START';
export const ROUTE_QUERY_SUCCESS = 'CORE/ROUTE_QUERY_SUCCESS';
export const ROUTE_QUERY_ERROR = 'CORE/ROUTE_QUERY_ERROR';
export const SET_PATH = 'CORE/SET_PATH';
