version: '3'
services:
  core:
    image: wlchs/oca.js:latest
    environment:
      - TZ=Europe/Amsterdam
      - NODE_ENV=production
      - OCA_IMPORT_FILE_DIR=/update_data
      - OCA_DB_HOST=db
      - OCA_DB_PORT=27017
      - OCA_DB_NAME=test
      - OCA_DB_USER=oca_admin
      - OCA_DB_PASSWORD=oca_password
    ports:
      - "4000:4000"
    links:
      - db
    restart: always
    volumes:
      - ./update_data:/update_data
  db:
    container_name: "db"
    image: mongo:latest
    command: mongod --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - oca.volume:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
volumes:
  oca.volume:
