export const PROJECT_LIST_QUERY_START = 'CUSTOM/PROJECT_LIST_QUERY_START';
export const PROJECT_LIST_QUERY_SUCCESS = 'CUSTOM/PROJECT_LIST_QUERY_SUCCESS';
export const PROJECT_LIST_QUERY_ERROR = 'CUSTOM/PROJECT_LIST_QUERY_ERROR';
