export const ROUTE_QUERY_START = 'LAYOUT/ROUTE_QUERY_START';
export const ROUTE_QUERY_SUCCESS = 'LAYOUT/ROUTE_QUERY_SUCCESS';
export const ROUTE_QUERY_ERROR = 'LAYOUT/ROUTE_QUERY_ERROR';
export const SET_PATH = 'LAYOUT/SET_PATH';
